### PR TITLE
add: baidu image

### LINKED ISSUE #43: Add https://image.baidu.com/ to image section
Add https://image.baidu.com/ to image section

### PR DESCRIPTION
**Pull request by vaishsabu**
closes #43

### CODE REVIEW

**Comment by edoardottt** [comment]
I don't know what description you choose (or where you got it), in general the decription should be the one used by the site (e.g. when you search for that domain on a search engine like google what it's written under the result you're looking for). SInce in this case I'm struggling to find the official description too, maybe it's better to stick with `Baidu Image Search` for the description

**Comment by vaishsabu** [comment]
ok will change the description

**Review by edoardottt — APPROVED** [review]
lgtm

**Comment by edoardottt** [comment]
Thank you so much for your contribution @vaishsabu ! :)

**Pull request merged**
