### PR TITLE
Added 2 new websites under servers.

### PR DESCRIPTION
**Pull request by biswabaibhab007**
Added 2 websites under servers.
- [PublicWWW](https://publicwww.com/) - A source code search engine that can help discover websites using specific technologies and vulnerabilities.

### CODE REVIEW

**Comment by edoardottt** [comment]
Regarding [OSINT Framework](https://osintframework.com/), we should add single online services in the list, not collection of.

**Comment by biswabaibhab007** [comment]
> Regarding [OSINT Framework](https://osintframework.com/), we should add single online services in the list, not collection of.

removed OSNIT framework

**Comment by biswabaibhab007** [comment]
but what about PublicWWW

**Comment by edoardottt** [comment]
> but what about PublicWWW

It's already in the list, see https://github.com/edoardottt/awesome-hacker-search-engines#code

**Pull request closed without merging**
